// 읽기 전용 · 142 기대충족 판정 엔진 스냅샷 (01 판단 탭 카드용) · 매수/매도 신호 아님
// 생성: build_dashboard_data.py · 소스: DAILY_MARKET_BRIEF_<TICKER>_v*_20261007.md
const MARKET_EXPECTATION_41 = {
  "_meta": {
    "generated_at": "2026-10-07",
    "description": "읽기 전용 · 142 기대충족 판정 엔진 스냅샷 (대시보드 01 판단 탭 카드용). 매수/매도 신호 아님.",
    "engine_md5_142": "81fbb72f38326575636ab15f52bbaf23",
    "composite_display_rule": "기본 화면에 composite 숫자 비표시(내부참고용 composite_internal_ref만 보관)"
  },
  "tickers": {
    "AAPL": {
      "ticker": "AAPL",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 7,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -2.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.2573,
      "support_summary": [
        "Q3 FY2026 매출 $109.417B, +16.3% YoY(FY2025 연간 6.4%보다 가속)",
        "영업이익 $35.695B, +26.6% YoY, 영업이익률 32.6%(전년동기 30.0%에서 개선)",
        "아이폰17·서비스 수요 호조(B급, 3개 이상 독립보도 교차확인 — 공식 1차 실적콜 원문은 이번 조사에서 직접 확인 못함)"
      ],
      "caution_summary": [
        "관세로 인한 비용 증가 우려, 가격 인상 가능성 시사(B급, 3개 이상 독립보도 교차확인 — 공식 10-Q 본문에서는 정량 수치 미확인)"
      ],
      "next_change_condition": [
        "관세 비용 영향이 공식 10-Q/8-K로 정량 확인되는 경우",
        "아이폰17·서비스 수요 호조가 공식 1차 소스(실적콜 원문)로 직접 확인되는 경우",
        "다음 공시에서 매출 성장률이 추가 가속/둔화되는 경우",
        "EPS 수정추세·목표가 상향/하향 비율 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_AAPL_v3_20261007.md",
      "primary_etf": "XLK",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 2.2,
      "stock_vs_primary_etf_relative_strength_pct": -3.59,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "AMAT": {
      "ticker": "AMAT",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 7,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -18.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-28",
      "consensus_snapshot_age_days": 9,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.4143,
      "support_summary": [
        "Q3 FY2026 매출 $9.115B, +25% YoY, 사상 최대(공식 8-K, 2026-08-13)",
        "CEO: \"AI 급속 도입이 전례없는 수요 견인, 2026 반도체시스템 매출 전망 추가 상향\"",
        "CAPEX $707M, CFO: \"2020년대 말까지 수요 전망 대응 제조역량 투자\""
      ],
      "caution_summary": [
        "중국 매출 비중 28%로 전년동기 35%에서 하락(원인은 공식 보도자료에 미명시, 수출통제 영향 가능성은 외부보도에서만 제기 — A급 공식근거로 확정되지 않음)"
      ],
      "next_change_condition": [
        "중국 매출비중 하락의 원인이 공식 공시(A급)로 확인될 경우(수출통제 vs 다른 요인)",
        "목표가 스냅샷 경과일이 14일을 넘기면 STALE_CONSENSUS_WARNING 적용 검토",
        "다음 공시에서 매출 YoY 성장률이 둔화되는 경우 → 라벨 재검토",
        "EPS 수정추세·목표가 상향/하향 비율 확보 시 → 결론 보강"
      ],
      "source_file": "DAILY_MARKET_BRIEF_AMAT_v3_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 5.07,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "AMD": {
      "ticker": "AMD",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": 2.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.7884,
      "support_summary": [
        "총매출 +50% YoY",
        "데이터센터 세그먼트 +107% YoY",
        "GAAP 영업이익 적자→흑자 전환"
      ],
      "caution_summary": [],
      "next_change_condition": [
        "Q3 2026 공시에서 데이터센터 매출 성장이 크게 둔화되는 경우",
        "Anthropic 2GW 계약의 구체적 물량·일정이 공식화되거나 축소되는 경우",
        "목표가 상향/하향 비율, EPS 수정 추세를 확보하면 → 가격위치-기대방향 관계 설명에 추가",
        "2차 목표가 제공자 또는 2차 142 증거 소스 확보 시 → 신뢰도 상한 B 해제 검토"
      ],
      "source_file": "DAILY_MARKET_BRIEF_AMD_v4_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 24.43,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "AMZN": {
      "ticker": "AMZN",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -22.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.04,
      "support_summary": [
        "AWS 매출 $42.2B, +36.7% YoY(\"18개 분기 중 가장 빠른 성장\", CEO Jassy, 영업이익률 39.4%)",
        "총매출 $200.6B, +20% YoY",
        "영업이익 $27.5B, +43% YoY, 영업이익률 13.7%(FY2025 연간 11.2%보다 개선)"
      ],
      "caution_summary": [
        "분기 FCF -$8.8B(음수) — CAPEX $54.2B가 OCF $45.4B 초과",
        "TTM CAPEX $169.0B, +64% YoY — FY2025 연간 전환율 0.096(142 v0.3 감사 확인)보다도 현금소진 가속"
      ],
      "next_change_condition": [
        "다음 분기 FCF·CAPEX 추이가 추가로 악화/개선되는 경우",
        "AWS 성장률(+36.7%)이 지속/둔화되는 경우",
        "부채·정책 축이 공식근거로 관측 가능해지는 경우",
        "EPS 수정추세·목표가 상향/하향 비율 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_AMZN_v3_20261007.md",
      "primary_etf": "XLY",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -8.44,
      "stock_vs_primary_etf_relative_strength_pct": 1.92,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "ANET": {
      "ticker": "ANET",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -13.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-30",
      "consensus_snapshot_age_days": 7,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.92,
      "support_summary": [
        "총매출 $3,036M, +37.7% YoY(사상 최초 $3B대 분기)",
        "상반기 OCF $2,777M, +50.7% YoY",
        "RPO $8.4B, 비취소성 구매약정 $9.7B(12개월 내 $9.4B) — 수요 지속의 공식 근거"
      ],
      "caution_summary": [
        "GAAP 매출총이익률 62.9%, 전년 65.2%에서 -2.3%p 하락(AI/클라우드 하드웨어 믹스 변화) — 영업레버리지가 이를 상쇄했으나 구조적 마진 압박 신호로 기록"
      ],
      "next_change_condition": [
        "다음 분기(Q3 2026, 2026년 11월경) 공시에서 매출총이익률 하락이 지속/반전되는지 확인",
        "CAPEX 분기 단독 수치가 공시되어 관측축 확대 시",
        "고객 집중도(상위 2개 고객 42%)가 추가로 심화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_ANET_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -0.41,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "ARM": {
      "ticker": "ARM",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": 2.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-18",
      "consensus_snapshot_age_days": 19,
      "consensus_age_warning": null,
      "stale_consensus_warning": true,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.7167,
      "support_summary": [
        "총매출 $1,289M, +22.4% YoY(데이터센터向 로열티 +22.2%)",
        "OCF $902M, +171.7% YoY",
        "AGI CPU(신규 실리콘) 수요 FYE27~28 누적 $2B 초과, Nvidia/Google/AWS·Meta/Microsoft/Qualcomm 신규 채택 공식 발표"
      ],
      "caution_summary": [
        "GAAP 영업이익 -20.2% YoY(마진 7.1%, AGI CPU 투자 확대로 영업비용 +27.8%) — 비GAAP 영업마진은 41.2%로 여전히 높음"
      ],
      "next_change_condition": [
        "GAAP 영업이익률이 다음 분기에 회복/추가 악화되는지 확인",
        "AGI CPU 등 신규 실리콘 매출이 실제로 인식되기 시작하는 시점",
        "목표가 소스 간 불일치가 해소되며 컨센서스가 수렴하는 경우",
        "Arm China 관련 새로운 공식 공시가 나오는 경우"
      ],
      "source_file": "DAILY_MARKET_BRIEF_ARM_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 8.47,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "ASML": {
      "ticker": "ASML",
      "as_of": "2026-10-07",
      "expectation_status": "증거 부족",
      "confidence": "매우낮음",
      "observed_axes": 2,
      "ab_grade_axes": 2,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": true,
      "consensus_position_pct": -15.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": true,
      "composite_internal_ref": null,
      "support_summary": [
        "2026년 연간 매출 가이던스를 올해 두 번째로 상향(€36~40B→€43~45B)",
        "CFO: 2027년 Low-NA EUV 주문이 \"거의 완전 확보\""
      ],
      "caution_summary": [
        "2026-06-19 미 상무장관이 ASML EUV 장비(또는 관련부품)의 수출통제 위반 중국 반입 가능성을 제기 — ASML CEO는 전면 반박, 2026-10-07 현재까지 미해결·미확정 상태"
      ],
      "next_change_condition": [
        "매출·이익·현금전환·CAPEX·부채 축의 명확한 YoY 비교치(ASML 데이터북/20-F급 자료) 확보 시 → 관측축 3개 이상 충족되면 정식 라벨로 재평가",
        "2026-06 수출통제 의혹이 공식적으로 해소되거나 제재로 확정되는 경우",
        "중국 매출 비중의 정상화(2026년 약 20% 전망)가 실제 분기 수치로 확인되는 경우",
        "목표가 상향/하향 비율 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_ASML_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -4.6,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "AVGO": {
      "ticker": "AVGO",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 4,
      "ab_grade_axes": 4,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -30.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-02",
      "consensus_snapshot_age_days": 5,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 1.0,
      "support_summary": [
        "총매출 $29,591M, +86% YoY(AI반도체 $16,700M +221%)",
        "비GAAP 영업이익 $20,095M, +92% YoY(마진 약 68%)",
        "Q4 FY26 AI반도체 매출 가이던스 $21.7B, +236% YoY(공식 가이던스)"
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(RPO·고객별 매출집중도 등 구체 수치는 2차 소스에서만 확인돼 counter_evidence로만 기록 — 참고용)"
      ],
      "next_change_condition": [
        "CAPEX 수치를 10-Q로 교차검증해 관측축 확대 시",
        "RPO·고객별 매출집중도가 공식 1차 문서(10-Q/실적콜 원문)로 확인되는 경우",
        "AI반도체 매출 성장률이 다음 분기 가이던스 대비 둔화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_AVGO_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -6.55,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "BE": {
      "ticker": "BE",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 8,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": 5.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.5065,
      "support_summary": [
        "Q2 2026 매출 $1,065.4M(+165.5% YoY), FY2026 가이던스 $3.9B~$4.2B로 상향",
        "Q2 2026 OCF $226.4M(전년동기 $(213.1)M 유출에서 플러스 전환)",
        "Brookfield-Bloom Energy AI 인프라 파트너십 $5B→$25B로 5배 확대(2026-06-30 공식 발표)"
      ],
      "caution_summary": [
        "총부채 약 $2,478M, 전년동기 대비 +120% YoY",
        "발행주식수 2.345억주→2.945억주, +25.9% YoY 희석(전환사채 전환·옵션·워런트 행사 등) — 둘 다 핵심 경계요인으로 아래에서 상술"
      ],
      "next_change_condition": [
        "다음 2개 분기 연속으로 OCF 플러스가 유지되는지 확인(현재는 1개 분기 데이터)",
        "추가 희석(전환사채 잔여물량 전환, 신규 ATM 증자 개시 여부) 확인",
        "부채 수준이 추가로 증가하는지, 신용조건이 변화하는지 확인",
        "Brookfield 파트너십의 실제 설치용량(GW)·매출인식 시점이 구체화되는지 확인"
      ],
      "source_file": "DAILY_MARKET_BRIEF_BE_v1_20261007.md",
      "primary_etf": "ICLN",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.96,
      "stock_vs_primary_etf_relative_strength_pct": 18.26,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "CEG": {
      "ticker": "CEG",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 8,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -15.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.1551,
      "support_summary": [
        "Q2 2026 영업수익 $7,504M(+23.0% YoY)",
        "H1 2026 CAPEX $2,521M(원전 증설·Crane/TMI 재가동)",
        "Meta와 Clinton 발전소 전량(1,121MW) 20년 PPA 체결(2027-06 개시)"
      ],
      "caution_summary": [
        "H1 2026 FCF 약 -$968M(마이너스, CAPEX가 OCF를 앞지름)",
        "GAAP 순이익 $513M, 전년 $839M 대비 -38.9%(Calpine 인수 관련 일회성 항목 추정)",
        "총부채 약 $24.7B(현금 $697M에 불과), 대규모 자사주매입과 동시 진행"
      ],
      "next_change_condition": [
        "Google PPA(890MW/$4.3B)가 공식 8-K/보도자료로 확인되는 경우",
        "다음 분기 공시에서 FCF가 플러스로 전환되거나 CAPEX 집행 속도가 둔화되는지 확인",
        "원자력 가동률 하락이 다음 분기에도 지속되는지(구조적 vs 일시적) 확인",
        "전력가격·헤지비율 공식 공시 확보 시 관측축 확대(9/9 목표)"
      ],
      "source_file": "DAILY_MARKET_BRIEF_CEG_v1_20261007.md",
      "primary_etf": "XLU",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -10.12,
      "stock_vs_primary_etf_relative_strength_pct": 4.94,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "COHR": {
      "ticker": "COHR",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -19.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.52,
      "support_summary": [
        "FY26 연간 매출 $7,118.2M, +22.5% YoY(데이터센터·통신 세그먼트 +40.5%)",
        "CAPEX FY+150% YoY(InP 레이저 생산능력 확충)",
        "CEO: \"AI 데이터센터가 구리에서 광통신으로 전환 중\" — FY2027이 \"실질적으로 예약 완료\"(2028년 calendar까지 주문)"
      ],
      "caution_summary": [
        "FY26 연간 OCF $79.5M, 전년 $633.6M 대비 -87.5% YoY(재고가 거의 2배 증가하며 운전자본 부담 급증)",
        "GAAP 순손실 $(6,935.1)M(전환사채 지분전환에 따른 비현금 상각손실 약 $7.8B 포함): 해당 GAAP 손실에는 비현금 평가·상각·손상 항목이 포함돼 있어 142의 특정 현금전환 또는 영업 흐름 점수에는 직접 반영하지 않았다. 다만 손상·상각은 자산가치, 투자효율, 과거 인수·투자 판단의 경고 요인일 수 있으므로 Daily Market Brief의 경계 요인에는 별도로 표시한다."
      ],
      "next_change_condition": [
        "다음 분기(Q1 FY2027, 2026년 9월말 마감) 공시에서 OCF가 회복되는지 확인",
        "NVIDIA 투자·공급계약 소식이 1차 문서(10-K)로 확인되는 경우",
        "BIS/Huawei 조사의 손실 범위가 구체화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_COHR_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 8.5,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "CRM": {
      "ticker": "CRM",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 4,
      "ab_grade_axes": 4,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -20.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-02",
      "consensus_snapshot_age_days": 5,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.7,
      "support_summary": [
        "OCF $1.269B, +71% YoY",
        "총매출 $11.345B, +11%(구독매출 +12%)",
        "비GAAP 영업마진 34.1%(GAAP 20.5%, 격차 13.6%p)"
      ],
      "caution_summary": [
        "이번 증거셋에서는 반대방향 A/B급 증거 없음(GAAP-비GAAP 마진 격차는 counter_evidence로 기록 — 참고용)"
      ],
      "next_change_condition": [
        "CAPEX·부채 데이터 확보 시 → 관측축 추가, 현금전환 그림 완성",
        "매출성장률이 추가로 둔화/가속되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_CRM_v3_20261007.md",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -19.51,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "EME": {
      "ticker": "EME",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -20.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.1289,
      "support_summary": [
        "Q2 2026 매출 $5,154.9M(+19.8% YoY)",
        "영업이익 $547.3M(+31.8% YoY), 순이익 $403.7M(+33.6% YoY)"
      ],
      "caution_summary": [
        "10-Q 공시: 고정가 건설계약 재추정에 따른 누적조정손실(cumulative catch-up adjustments) Q2 $37.4M, H1 $47.1M",
        "H1 2026 OCF $289.9M, 전년 $302.2M 대비 -4.0%(이익 성장에도 불구 현금전환은 오히려 악화)"
      ],
      "next_change_condition": [
        "다음 분기 공시에서 고정가 계약 재추정손실이 추가로 발생하는지, 해소되는지 확인",
        "OCF가 매출채권 회수 개선으로 반등하는지 확인",
        "RPO/데이터센터 수요 근거가 공식 문서(8-K/IR)로 교차확인되는 경우",
        "총부채/순부채 수치 확보 시 부채축 재평가"
      ],
      "source_file": "DAILY_MARKET_BRIEF_EME_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 11.43,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "ETN": {
      "ticker": "ETN",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 8,
      "ab_grade_axes": 8,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -3.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.3125,
      "support_summary": [
        "Q2 2026 매출 $8.531B(+21% YoY, 유기 +14%)",
        "Electrical Americas 백로그 +33% YoY, Electrical Global 백로그 +103% YoY",
        "Adjusted EPS $3.15로 사상최고 경신"
      ],
      "caution_summary": [
        "장기부채가 6개월 만에 $8.758B→$18.509B로 약 +$9.75B 급증($8.5B 선순위채 발행, Boyd Thermal 인수자금 조달 목적)",
        "GAAP 순이익 $821M, 전년 $982M 대비 감소(GAAP EPS -16%)"
      ],
      "next_change_condition": [
        "Dana와의 Mobility 분리합병이 예정대로 2027 Q1에 종결되는지 확인",
        "다음 분기 운전자본(재고·매출채권) 세부 데이터 확보 시 관측축 확대",
        "GAAP 순이익 감소의 구체적 원인(일회성 비용 항목)이 10-Q/10-K에서 확인되는 경우",
        "Mobility 세그먼트 유기적 매출 역성장(-2%)이 지속/심화되는지 확인"
      ],
      "source_file": "DAILY_MARKET_BRIEF_ETN_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 10.44,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "FIX": {
      "ticker": "FIX",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -17.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.8917,
      "support_summary": [
        "Q2 2026 매출 $3.27B(+50% YoY), H1 $6.13B(+53%)",
        "매출총이익률 25.8%(전년 23.5%), 영업이익 +86%, 순이익 +91%",
        "RPO(수행의무잔액) $14.06B, YoY +$5.9B"
      ],
      "caution_summary": [
        "기술(데이터센터)고객 비중이 Q2 매출의 58%까지 집중(전년 43%) — 단일 최대 전방산업 의존도 급상승",
        "H1 2026 OCF $1.53B 급증(전년 대비 약 +830%)의 상당부분은 계약부채(고객 선수금) +$1.06B 증가에 기인한 타이밍 효과"
      ],
      "next_change_condition": [
        "기술고객 집중도(58%)가 추가로 심화되는지, 하이퍼스케일러 CAPEX 계획 변화 신호가 나타나는지 확인",
        "마진 개선(+약300bp)이 다음 분기에도 유지되는지(모듈러 믹스 효과의 지속성) 확인",
        "신규 모듈러 생산시설 투자의 가동률·수익성이 확인되는 경우",
        "노동·자재 인플레이션 관련 정량 공시 확보 시 관측축 보강"
      ],
      "source_file": "DAILY_MARKET_BRIEF_FIX_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 15.0,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "GEV": {
      "ticker": "GEV",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 8,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -16.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.6119,
      "support_summary": [
        "Q2 2026 총매출 $11,104M(+22% YoY, 유기 +12%)",
        "Q2 2026 OCF $5,492M, FY2026 FCF 가이던스 $11.5~12.5B로 상향(기존 $6.5~7.5B 대비 큰 폭 상향)",
        "Q2 2026 수주 $24.2B(+88% 유기 YoY), 가스발전 설비백로그 53GW·슬롯예약 63GW로 확대"
      ],
      "caution_summary": [
        "2026-02-04 공개기업 전환 후 첫 회사채 $2.6B 발행, 총부채가 2025년말 대비 +211%(2차 집계) 증가",
        "(이익축 관련, 아래 Batch4 특화항목 참조) 헤드라인 GAAP 순이익의 상당부분이 비반복 M&A 회계효과",
        "육상풍력 부문은 OBBBA 입법 이후 세액공제 요건 강화로 정책 역풍(단일 2차소스, 저신뢰도)"
      ],
      "next_change_condition": [
        "Q2 2026 조정 EBITDA 공식수치 확보 시 이익축 신뢰도 복원(현재 B로 하향됨)",
        "가스터빈 백로그 수치의 1차/2차 소스 불일치(53GW vs 116GW) 해소",
        "OBBBA 풍력 정책 영향이 공식 자료로 재확인되는지 확인",
        "다음 분기 OCF 급증이 일시적 선수금 효과인지 구조적 개선인지 확인"
      ],
      "source_file": "DAILY_MARKET_BRIEF_GEV_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 11.37,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "GOOGL": {
      "ticker": "GOOGL",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -19.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.05,
      "support_summary": [
        "Q2 2026 매출 $119.8B, +24% YoY(FY2025 연간 15.1%보다 가속)",
        "Google Cloud +82% 성장, \"Fortune 100의 90%가 Gemini Enterprise 사용\"",
        "영업이익률 34%(전년동기 대비 +2%p)"
      ],
      "caution_summary": [
        "분기 FCF -$5.8B(음수) — CAPEX $44.9B가 OCF $39.1B를 초과(이 둘은 별개 사실: FCF 적자 자체와 자금조달 방식은 구분해서 기록)",
        "같은 분기 중 $49.6B 유상증자 + $20.3B 채무 조달이 있었고, 공식공시 원문에 그 목적이 \"AI 인프라·글로벌 컴퓨팅 확장\"이라고 명시됨(이 조달이 CAPEX·FCF 적자를 메우기 위한 것이라는 해석은 우리가 추가한 것이 아니라 원문 표현 그대로이며, 그 이상의 인과관계를 단정하지 않음)",
        "FY2025 연간 전환율도 0.568로 2021년 이후 지속 하락(142 v0.3 감사 확인)",
        "신규 채무 조달로 레버리지 증가"
      ],
      "next_change_condition": [
        "다음 분기 FCF가 양전환되거나 추가로 악화되는 경우 → 라벨 재평가",
        "유상증자·채무 조달 규모가 추가로 확대되는 경우 → 재무건전성 경계요인 강화",
        "클라우드 성장률(+82%)이 둔화되는 경우 → 지지근거 약화",
        "EPS 수정추세·목표가 상향/하향 비율 확보 시 → 결론 보강"
      ],
      "source_file": "DAILY_MARKET_BRIEF_GOOGL_v3_20261007.md",
      "primary_etf": "XLC",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.0,
      "stock_vs_primary_etf_relative_strength_pct": 3.06,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "HUBB": {
      "ticker": "HUBB",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -15.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-07-13",
      "consensus_snapshot_age_days": 86,
      "consensus_age_warning": null,
      "stale_consensus_warning": true,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.15,
      "support_summary": [
        "Q2 2026 매출 $1,711.8M(+15% YoY, 유기 +10%)",
        "조정 희석 EPS $5.52(+12% YoY)",
        "CEO 공식 발언: 그리드 현대화·부하 증가·데이터센터 투자 메가트렌드가 유기성장 견인"
      ],
      "caution_summary": [
        "총부채 $5,372.6M, 순부채 $4,874.2M(NSI Industries 인수 자금조달: $900M 텀론+$1.9B 선순위채)",
        "Q2 조정영업마진 23.9%로 전년대비 -50bp 하락(매출성장에도 불구)"
      ],
      "next_change_condition": [
        "최신(2026년 10월 전후) 다수 애널리스트 컨센서스 자료를 확보해 목표가 데이터를 갱신",
        "정량화된 백로그/수주 $ 수치가 공시되어 CAPEX-수요 페어링이 가능해지는 경우",
        "다음 분기 마진이 회복되는지, 인수 통합비용이 해소되는지 확인",
        "10-Q 전체 운전자본 세부내역 확보 시 현금전환 축 재평가"
      ],
      "source_file": "DAILY_MARKET_BRIEF_HUBB_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 7.46,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "INTC": {
      "ticker": "INTC",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -2.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.54,
      "support_summary": [
        "총매출 $16.1B, +25% YoY(DCAI +59%)",
        "GAAP 영업이익 +$1.8B(마진 11.1%)로 흑자전환(전년 -$3.2B)",
        "CEO: \"15년 내 최고 매출성장\" — Foundry 영업손실도 -$2.1B로 축소(전년 -$3.2B)"
      ],
      "caution_summary": [
        "상반기 CAPEX $6.2B, 전년 $8.7B 대비 -28.7% YoY(증설 서사와 달리 실제 투자는 감소 — 수요축과 분리해 기록)",
        "GAAP 순손실 -$11.0B(정부 관련 에스크로 주식의 비현금 공정가치 평가손실 약 $13.6B 포함): 해당 GAAP 손실에는 비현금 평가·상각·손상 항목이 포함돼 있어 142의 특정 현금전환 또는 영업 흐름 점수에는 직접 반영하지 않았다. 다만 손상·상각은 자산가치, 투자효율, 과거 인수·투자 판단의 경고 요인일 수 있으므로 Daily Market Brief의 경계 요인에는 별도로 표시한다."
      ],
      "next_change_condition": [
        "Foundry 외부고객 매출이 공식 수치로 확인되는 경우(1차 문서 확보 시)",
        "CAPEX가 다음 분기에 다시 증가 전환하는지, 그것이 수요와 어떻게 연결되는지 확인",
        "18A/14A 수율·고객계약이 공식적으로 확인되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_INTC_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 5.88,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "KLAC": {
      "ticker": "KLAC",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -14.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.35,
      "support_summary": [
        "FY26 연간 매출 $13,579M, +11.7% YoY",
        "backlog $7.86B→$12.57B(+60%), 10-K: \"강한 AI 인프라 빌드아웃 수요\"",
        "FY26 연간 순이익 +18.9% YoY"
      ],
      "caution_summary": [
        "순현금 포지션이 순부채로 전환(FY25 순현금 약 $1.39B→FY26 순부채 약 $985M, 대규모 배당·바이백에 따른 현금소진)",
        "중국 매출 비중 FY24 43%→FY25 33%→FY26 30%로 지속 하락(10-K가 수출규제를 직접 원인으로 서술)"
      ],
      "next_change_condition": [
        "다음 분기(FY27 Q1, 2026년 10월 하순 예정) 공시에서 분기 OCF가 회복되는지 확인",
        "순부채 전환이 일회성 자본환원 때문인지 구조적 변화인지 다음 분기로 확인",
        "중국 매출 비중이 추가로 하락하거나 안정화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_KLAC_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -5.16,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "LITE": {
      "ticker": "LITE",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 4,
      "ab_grade_axes": 4,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -5.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.9,
      "support_summary": [
        "Q4 FY26 매출 $1,006.3M, +109.3% YoY(FY 연간 +83.2%)",
        "총부채 -36.4% YoY(전환사채 지분전환으로 순현금 전환)",
        "CEO: \"AI 컴퓨트 워크로드 확대의 중심\" — Q1 FY27 가이던스가 목표모델을 한 분기 앞당겨 달성할 수준으로 상향"
      ],
      "caution_summary": [
        "고객 집중도: Customer A가 FY26 매출의 26.6%까지 확대(전년 15.4%) — 특정 대형고객 의존도 상승",
        "GAAP 순손실(전환사채 지분전환에 따른 비현금 상각손실 포함): 해당 GAAP 손실에는 비현금 평가·상각·손상 항목이 포함돼 있어 142의 특정 현금전환 또는 영업 흐름 점수에는 직접 반영하지 않았다. 다만 손상·상각은 자산가치, 투자효율, 과거 인수·투자 판단의 경고 요인일 수 있으므로 Daily Market Brief의 경계 요인에는 별도로 표시한다."
      ],
      "next_change_condition": [
        "10-K 원문에서 영업현금흐름·CAPEX를 직접 확인해 관측축 확대 시",
        "고객 집중도(26.6%)가 추가로 심화되는지 확인",
        "다음 분기(Q1 FY2027) 공시에서 목표모델 조기달성이 실제로 재확인되는지",
        "목표가 상향/하향 비율 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_LITE_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 17.06,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "LRCX": {
      "ticker": "LRCX",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -13.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-05",
      "consensus_snapshot_age_days": 2,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.5667,
      "support_summary": [
        "Q4 FY2026 매출 $6,722M, +30.0% YoY(FY연간 +26.0%)",
        "Q4 GAAP 영업이익 +44.3% YoY(마진 37.4%, 전년 33.7%)",
        "CEO: \"AI발 수요가 반도체산업 재편\" — 다음 분기 매출 가이던스 $8.10B±$400M(20%대 추가 성장 시사)"
      ],
      "caution_summary": [
        "FY2026 연간 OCF -5.1% YoY(매출 +26% 증가에도 역행)",
        "10-K: 중국向 매출이 수출 라이선스 규제로 실질적 영향을 받아왔음(중국 비중 FY2024 42.3%→FY2026 33.8%로 하락)"
      ],
      "next_change_condition": [
        "다음 분기(9월) 공식 실적에서 OCF가 회복되는지 확인",
        "중국 매출 비중이 추가로 하락하거나 안정화되는 경우",
        "CAPEX/OCF 비율이 추가로 악화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_LRCX_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -3.02,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "META": {
      "ticker": "META",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -8.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.2,
      "support_summary": [
        "총매출 $60.8B, +28% YoY",
        "CAPEX $31.1B(+88%), 2026 가이던스 $130~145B로 상향",
        "Zuckerberg: \"AI가 핵심사업을 가속하고 신규 기업시장 기회를 열고 있다\""
      ],
      "caution_summary": [
        "OCF $31.9B(+25%), CAPEX $31.1B(+88%) → FCF $0.8B(-91% YoY, 급감)",
        "영업이익 $18.8B(-8% YoY), 영업마진 31%(전년 43%에서 -12%p 하락)"
      ],
      "next_change_condition": [
        "다음 분기 영업마진이 추가로 하락/회복되는 경우",
        "FCF가 회복세를 보이는 경우",
        "부채축 데이터 확보 시 → 관측축 추가",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_META_v3_20261007.md",
      "primary_etf": "XLC",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.0,
      "stock_vs_primary_etf_relative_strength_pct": 20.14,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "MOD": {
      "ticker": "MOD",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -28.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.25,
      "support_summary": [
        "Q1 FY2027 순매출 $874.1M(+28% YoY, 유기 +24%)",
        "CEO 공식 발언: 3개 분기 연속 기록적 수주로 백로그가 1년간 거의 2배 증가, Data Centers 세그먼트 매출 +90% YoY",
        "순이익 $74.3M(+44% YoY)"
      ],
      "caution_summary": [
        "Data Centers 세그먼트 총이익률 20.2%, 전년대비 -960bp(세그먼트 매출 +90% YoY에도 불구, 공급망 제약·생산비효율·원재료비·보증비용 증가가 원인)",
        "FCF -$5.0M(전년 +$0.2M), 재고 +$102.9M 분기 순증"
      ],
      "next_change_condition": [
        "다음 분기 Data Centers 세그먼트 마진이 회복되는지, 공급망 제약이 해소되는지 확인",
        "FCF가 플러스로 재전환하는지, 재고 수준이 정상화되는지 확인",
        "정확한 백로그 달러 수치가 공시되어 수요축 근거가 보강되는 경우",
        "목표가 상향/하향 비율, 추가 애널리스트 커버리지 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_MOD_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": -0.33,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "MRVL": {
      "ticker": "MRVL",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -3.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.9333,
      "support_summary": [
        "총매출 $2,739.3M, +37% YoY(데이터센터 $2,171.5M, 79%, +46% YoY)",
        "비GAAP 영업이익 $1,003.2M, +103.6% YoY(마진 36.6%)",
        "CEO: \"AI 관련 수주가 매우 견고\" — Q3 가이던스 $3,150M±5%(약 +36% YoY)"
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(세그먼트 분류가 이번 분기부터 2분류로 축소돼 과거 5분류 추세와 직접 비교 불가하다는 점만 counter_evidence로 기록 — 참고용)"
      ],
      "next_change_condition": [
        "데이터센터 매출 성장률이 다음 분기에 추가 가속/둔화되는 경우",
        "새 2분류 세그먼트 기준으로 1~2개 분기 추세가 축적되면 재평가",
        "중국向 출하 비중이 수출규제로 인해 급격히 변화하는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_MRVL_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 16.84,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "MSFT": {
      "ticker": "MSFT",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -9.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.8667,
      "support_summary": [
        "총매출 $90.0B, +18% YoY(공식 8-K)",
        "GAAP 영업이익 $40.6B, +18%, 마진 45.1%",
        "CAPEX $35.8B(+110%) — AI/클라우드 데이터센터 확장"
      ],
      "caution_summary": [
        "이번 증거셋에서는 반대방향 A/B급 증거 없음(현금전환 축의 counter_evidence에 \"CAPEX 증가율(110%)이 OCF 증가율(30%)을 크게 앞질러 현금전환 질 저하\"를 기록해둠 — 참고용)"
      ],
      "next_change_condition": [
        "다음 분기 CAPEX/OCF 비율이 추가로 악화되는 경우",
        "Azure/클라우드 성장률이 둔화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_MSFT_v3_20261007.md",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -0.38,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "MU": {
      "ticker": "MU",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -33.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 1.0,
      "support_summary": [
        "FQ4 FY2026 총매출 $54,229M, +379% YoY(FY연간 +256%)",
        "FQ4 GAAP 영업이익률 80.7%(FY연간 74.6%, 전년 26.1%)",
        "CEO Sanjay Mehrotra: \"AI가 Super Intelligence로 진화 중이며 메모리가 이를 가능케 한다\" — FQ1 FY2027 매출 가이던스 $61.5B±$1.5B(추가 성장 시사)"
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(증가폭이 역사적으로 이례적인 수준이라 사이클 정점·되돌림 리스크는 counter_evidence로만 기록 — 참고용)"
      ],
      "next_change_condition": [
        "다음 분기(FQ1 FY2027, 2026년 12월경) 공시에서 매출·마진이 가이던스대로 유지되는지, 혹은 사이클 정점 신호가 나오는지 확인",
        "HBM/DRAM/NAND 가격이 둔화·반전되는 경우",
        "분석가 목표가 분산이 좁아지며 컨센서스가 수렴하는 경우",
        "중국 매출 비중·수출규제 영향이 공식 문서(10-K)로 확인되는 경우"
      ],
      "source_file": "DAILY_MARKET_BRIEF_MU_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -8.7,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "NVDA": {
      "ticker": "NVDA",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 5,
      "ab_grade_axes": 5,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -24.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.52,
      "support_summary": [
        "Q2 FY2027 매출 +106% YoY(공식 8-K)",
        "비GAAP 영업마진 66.2% 유지",
        "AI 데이터센터 수요 지속(Huang 발언)"
      ],
      "caution_summary": [
        "부채축 미관측",
        "정책(수출규제)축 A/B급 근거 미확정",
        "뉴스/추세 데이터 공백"
      ],
      "next_change_condition": [
        "다음 10-Q/8-K에서 매출 YoY 성장률이 70% 이하로 확인 → 기대 라벨 하향 검토",
        "수출규제 강화가 A/B급 공식근거로 확인 → 구조위험 재평가",
        "EPS 컨센서스 수정 추세(상향/하향 비율)를 확보하면 → 가격위치-기대방향 관계를 설명하는 근거로 추가",
        "2차 목표가 제공자 확보 시 → CONSENSUS_SOURCE_CONCENTRATION_WARNING 해제 검토"
      ],
      "source_file": "DAILY_MARKET_BRIEF_NVDA_v4_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -7.7,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "ORCL": {
      "ticker": "ORCL",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 7,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -40.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-25",
      "consensus_snapshot_age_days": 12,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.6571,
      "support_summary": [
        "Q1 FY2027 총매출 $19,345M(+30% YoY), 클라우드 $11,607M(+62% YoY, OCI만 +121% YoY)",
        "GAAP 영업이익 $6,728M(+57% YoY, 마진 35%), GAAP 순이익 $4,760M(+63% YoY)",
        "Q1 FY2027 OCF $23,103M(+184% YoY)"
      ],
      "caution_summary": [
        "Q1 FY2027 FCF 약 -$5,396M(마이너스) — CAPEX($28,499M)가 OCF 증가를 크게 상회.",
        "OCF $23.1B 중 $11,363M은 AI 계약 관련 금융요소가 포함된 고객 선수금 증가분으로, 순수 경상적 영업현금창출이 아닌 금융구조성 선수금이 상당부분을 차지함(헤드라인 OCF 증가율을 액면 그대로 해석하지 않음)",
        "$20B 지분증자(ATM)로 기존 주주 지분희석 발생(부채 감소와 동시에 진행)"
      ],
      "next_change_condition": [
        "Q2 FY2027 공식 실적에서 가이던스(매출성장 30~34%) 달성 여부 확인",
        "FCF가 마이너스에서 플러스로 전환되는 시점, CAPEX 피크 여부 확인",
        "OCF 중 금융구조성 선수금 비중이 다음 분기에도 유지되는지 확인",
        "목표가 상향/하향 비율, 41종목 통합표 반영 시 라벨 변경을 명확히 각주 처리"
      ],
      "source_file": "DAILY_MARKET_BRIEF_ORCL_v4_20261007.md",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -15.13,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "PLTR": {
      "ticker": "PLTR",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 4,
      "ab_grade_axes": 4,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -6.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 1.0,
      "support_summary": [
        "총매출 $1.935B, +93% YoY(美상업 +149%)",
        "GAAP 영업마진 47%, 비GAAP 62%",
        "OCF $1.216B, 조정FCF $1.220B"
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(초고성장 구간의 기저효과 가능성은 counter_evidence로 기록 — 참고용)"
      ],
      "next_change_condition": [
        "CAPEX·부채 공식수치 확보 시 → 관측축 확대, 현재 그림이 바뀔 수 있음",
        "93% 성장률이 기저효과 없이 다음 분기에도 유지되는지 확인",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_PLTR_v3_20261007.md",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": 3.87,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "PWR": {
      "ticker": "PWR",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -6.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.693,
      "support_summary": [
        "Q2 2026 매출 $9.56B(+41.1% YoY, 유기 27.4%)",
        "연결 백로그 $53.4B 사상최고(Electric Infrastructure $43.8B, Underground $9.7B)",
        "순이익 $451M(+96.9% YoY)"
      ],
      "caution_summary": [
        "매출채권 $8,532.3M(6/30/26), YE2025 대비 +약 25% 증가",
        "H1 2026 OCF 급증($1,487.2M, +176%)의 상당부분이 계약부채(선수금) 증가(+$983.5M)에 기인한 운전자본·타이밍 효과"
      ],
      "next_change_condition": [
        "2026 가이던스(특히 Technology&Load Centers +220~240%)의 실제 달성 여부 확인",
        "매출채권 증가 추세가 완화되는지, 회수 지연 신호가 나타나는지 확인",
        "$2.0B 신규 선순위채 발행의 8-K 원문 직접 확인(현재 2차 집계 사용)",
        "정책·뉴스·추세 축 보강(현재 미관측)"
      ],
      "source_file": "DAILY_MARKET_BRIEF_PWR_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 17.34,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "QCOM": {
      "ticker": "QCOM",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": 3.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-23",
      "consensus_snapshot_age_days": 14,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.0333,
      "support_summary": [
        "자동차 23개 분기 연속 두 자릿수 YoY 성장, 비핸드셋 매출 목표 FY2029까지 $40B 상향",
        "CAPEX 9개월 YTD $1.578B, 전년대비 약 2배(자동차·IoT 수요 뒷받침)"
      ],
      "caution_summary": [
        "총매출 -4% YoY(핸드셋 -20% YoY가 주원인)",
        "GAAP 영업이익 -41% YoY(마진 16.4%, 전년 26.6%)",
        "9개월 YTD OCF -16% YoY"
      ],
      "next_change_condition": [
        "다음 공시(FQ4 FY2026, 2026-11월경)에서 핸드셋 매출 추가 둔화/회복 확인 시",
        "자동차+IoT 성장률이 가속/둔화되는 경우",
        "재고 증가가 추가 확대되는 경우(과잉비축 신호)",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_QCOM_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -4.27,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "SNDK": {
      "ticker": "SNDK",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -22.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-07",
      "consensus_snapshot_age_days": 0,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.9333,
      "support_summary": [
        "Q4 FY26 매출 $8,965M, +372% YoY(분사 후 깨끗한 분기 비교)",
        "GAAP 영업이익 $7,037M(마진 84.6%), 전년 $18M에서 극적 개선",
        "장기채무 전액 상환($0, 전년 $1,829M) → 순현금 전환"
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(매출채권이 매출보다 더 빠르게 증가(+341% YoY)한 점은 counter_evidence로만 기록 — 참고용)"
      ],
      "next_change_condition": [
        "다음 분기(FY2027 Q1, 2026-10-29 예정) 공시에서 가격 vs 물량 기여도 추이, NBM 계약 추가 체결 확인",
        "매출채권 증가 추세가 완화되는지 확인",
        "현재가 소스 간 불일치가 해소되며 데이터 신뢰도가 개선되는 경우",
        "NAND 가격이 둔화·반전되는 경우"
      ],
      "source_file": "DAILY_MARKET_BRIEF_SNDK_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -16.12,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "STX": {
      "ticker": "STX",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 7,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -30.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-05",
      "consensus_snapshot_age_days": 2,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.7723,
      "support_summary": [
        "FY2026 연간 매출 +34.1% YoY(Q4 단독 +48.5%)",
        "FY2026 연간 GAAP 영업이익 +117% YoY(마진 33.6%, 전년 20.8%)",
        "FY2026 연간 OCF +239% YoY"
      ],
      "caution_summary": [
        "2026-10-02 Toshiba 필리핀 HDD 생산능력 2배 확대 발표(중기 점유율 목표 약 30%) 전후로 STX 주가 하락이 보도됨 — 두 사건의 직접 인과관계는 확인되지 않았으며, 공급 확대 우려 가능성을 뉴스축의 B급 경계 요인으로 기록"
      ],
      "next_change_condition": [
        "2026-10-27 Q1 FY2027 실적에서 가격결정력(마진)이 유지되는지, Toshiba 뉴스의 실질 영향이 나타나는지 확인",
        "BIS settlement agreement의 세부 조건이 공식 문서로 확인되는 경우",
        "Toshiba 생산능력 확대가 실제 양산·출하로 이어지는 시점(통상 1~2년 소요) 추적",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_STX_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -16.69,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "TSLA": {
      "ticker": "TSLA",
      "as_of": "2026-10-07",
      "expectation_status": "기대 유지",
      "confidence": "보통",
      "observed_axes": 8,
      "ab_grade_axes": 7,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -6.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-09-28",
      "consensus_snapshot_age_days": 10,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.1701,
      "support_summary": [
        "H1 2026 총매출 $50.6B(+21% YoY)",
        "H1 2026 OCF $8.6B(+84% YoY), 유동성 $43.5B",
        "H1 2026 CAPEX $8.3B(+113% YoY, 생산능력·AI투자 확대)"
      ],
      "caution_summary": [
        "Q2 2026 영업이익 $398M, 전년동기 $923M 대비 -57% YoY(매출 성장에도 마진 급격 압박)",
        "자동차 규제크레딧 매출이 분기간 $439M→$146M로 급감(이익 쿠션 약화)",
        "CAPEX 급증으로 FCF가 약 $352M 수준으로 얇아짐"
      ],
      "next_change_condition": [
        "2026-10-21 Q3 2026 10-Q/실적발표에서 영업이익률이 반등하는지, 규제크레딧 매출 추세가 어떻게 되는지 확인",
        "자동차 인도대수 YoY 감소가 다음 분기에도 지속되는지(구조적 수요둔화 vs 일시적) 확인",
        "CAPEX 증가가 로보틱스/AI 투자인지 자동차 생산능력인지 구체 분리공시되는 경우",
        "로보택시/Optimus의 실제 감사된 생산·매출 수치가 공식 문서로 공시되는 경우"
      ],
      "source_file": "DAILY_MARKET_BRIEF_TSLA_v1_20261007.md",
      "primary_etf": "IDRV",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -14.59,
      "stock_vs_primary_etf_relative_strength_pct": 16.44,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "TSM": {
      "ticker": "TSM",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "낮음",
      "observed_axes": 3,
      "ab_grade_axes": 3,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -10.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-05",
      "consensus_snapshot_age_days": 2,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 1.0,
      "support_summary": [
        "총매출 US$40.20B, +33.7% YoY(HPC 플랫폼 비중 66%)",
        "순이익률 55.6%, 순이익 +77.4% YoY",
        "CEO: \"첨단패키징 용량이 고객 성장을 제약할 정도로 타이트\", \"수요-공급 격차가 매우 크다\""
      ],
      "caution_summary": [
        "반대방향 A/B급 증거 없음(해외 파운드리 확장이 매출총이익률을 초기 2~3%p, 양산확대 시 3~4%p까지 희석할 수 있다는 회사 자체 언급만 counter_evidence로 기록 — 참고용)"
      ],
      "next_change_condition": [
        "영업현금흐름·CAPEX 분기 YoY·부채총액을 20-F/데이터북에서 확보해 관측축 확대 시",
        "해외(애리조나 등) 파운드리 확장에 따른 매출총이익률 희석이 실제로 가시화되는지 확인",
        "2nm 램프업이 3Q26 실제 실적으로 확인되는 경우",
        "ADR 목표가 상향/하향 비율 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_TSM_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 0.9,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "VRT": {
      "ticker": "VRT",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 6,
      "ab_grade_axes": 6,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -22.0,
      "current_price_as_of": "2026-10-02",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-02",
      "consensus_snapshot_age_days": 5,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": true,
      "composite_hidden": false,
      "composite_internal_ref": 0.7,
      "support_summary": [
        "Q2 2026 순매출 $3,274M(+24% YoY, 유기 +18%)",
        "영업이익 $638M(+44% YoY), 조정영업마진 22.6%(+410bp)",
        "H1 2026 OCF $1,867M(+198% YoY)"
      ],
      "caution_summary": [
        "H1 2026 재고 +$1,066M, 매출채권 +$641M 증가(운전자본 큰 폭 증가, 이연수익 증가가 일부 상쇄)",
        "가장 최근(Q2 2026) 공식 발표에는 갱신된 백로그/book-to-bill 수치가 공시되지 않음 — 현재 통용되는 \"백로그 $15B\" 수치는 2025년 12월말 기준으로 약 7개월 경과"
      ],
      "next_change_condition": [
        "다음 분기(Q3 2026) 공시에서 백로그/book-to-bill 수치가 갱신되는지 확인(현재 관측 공백)",
        "운전자본 증가 추세가 완화되는지 확인",
        "마진 개선(+410bp)이 다음 분기에도 유지되는지(일시적 타이밍 효과였는지) 확인",
        "52주 범위 데이터 확보 시 관측축 보강"
      ],
      "source_file": "DAILY_MARKET_BRIEF_VRT_v1_20261007.md",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": -7.66,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "VST": {
      "ticker": "VST",
      "as_of": "2026-10-07",
      "expectation_status": "기대 강화",
      "confidence": "보통",
      "observed_axes": 9,
      "ab_grade_axes": 8,
      "coverage_limited": false,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -25.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-06",
      "consensus_snapshot_age_days": 1,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": false,
      "composite_internal_ref": 0.3569,
      "support_summary": [
        "Q2 2026 Ongoing Operations Adjusted EBITDA $1,767M(+31.0% YoY)",
        "H1 2026 OCF $2,222M(+89.8% YoY)",
        "Helix Digital Infrastructure(KKR·쿠웨이트투자청·NVIDIA 공동) AI 인프라 JV 발표, Vistra 출자한도 $1.0B"
      ],
      "caution_summary": [
        "Q2 2026 영업수익 $4,017M, 전년 $4,250M 대비 -5.5% YoY(가격·물량 믹스·헤지 정산 효과)",
        "총부채 +$2.55B 증가(6개월간), 현금은 $785M→$435M로 감소",
        "Q2 GAAP 순이익 $305M, 전년 $327M 대비 -6.7%"
      ],
      "next_change_condition": [
        "Cogentrix 인수가 공식적으로 종결되는지 확인",
        "연방 대출 지원설이 공식 확인되거나 철회되는지 확인",
        "2028년 헤지비율(현재 72%)이 실제 가격상승 수혜로 이어지는지 다음 분기 이후 확인",
        "두 제공처 간 목표가 불일치가 해소되는지 확인"
      ],
      "source_file": "DAILY_MARKET_BRIEF_VST_v1_20261007.md",
      "primary_etf": "XLU",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -10.12,
      "stock_vs_primary_etf_relative_strength_pct": 11.96,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    },
    "WDC": {
      "ticker": "WDC",
      "as_of": "2026-10-07",
      "expectation_status": "증거 부족",
      "confidence": "매우낮음",
      "observed_axes": 2,
      "ab_grade_axes": 2,
      "coverage_limited": true,
      "source_concentration_warning": true,
      "currency_mismatch_warning": false,
      "consensus_position_pct": -37.0,
      "current_price_as_of": "2026-10-06",
      "expectation_as_of": "2026-10-07",
      "sector_environment_as_of": "2026-10-06",
      "consensus_snapshot_as_of": "2026-10-05",
      "consensus_snapshot_age_days": 2,
      "consensus_age_warning": null,
      "stale_consensus_warning": false,
      "price_as_of_mismatch": false,
      "composite_hidden": true,
      "composite_internal_ref": null,
      "support_summary": [
        "Q4 FY2026 매출 +44% YoY(FY연간 +36%)",
        "나얼라인 231EB 출하(+22% YoY), 클라우드향 매출 비중 89%(+43% YoY)"
      ],
      "caution_summary": [],
      "next_change_condition": [
        "이익·현금전환·CAPEX·부채 축의 명확한 YoY 비교치(10-K 상세 주석) 확보 시 → 관측축 3개 이상, A/B급 2개 이상 충족되면 정식 라벨(강화/유지/약화)로 재평가",
        "10-06 급락의 원인(업종 전반 vs 종목 고유 이슈)이 확인되는 경우",
        "나얼라인 출하 성장률이 다음 분기에 가속/둔화되는 경우",
        "목표가 상향/하향 비율, EPS 수정추세 확보 시"
      ],
      "source_file": "DAILY_MARKET_BRIEF_WDC_v1_20261007.md",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -23.62,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용"
    }
  }
};
