// 읽기 전용 · ETF 섹터 환경 필터 스냅샷 (01 판단 탭 카드용) · 매수/매도 신호 아님 — 신규 진입 속도 조절 참고정보
// 생성: build_dashboard_data.py · 소스: ETF_ENVIRONMENT_SNAPSHOT_v1_20261007.md / combined_final.json
// 2026-10-08 수정: sector_filter_interpretation_detail의 진입우선순위 문구를 SECTOR_FILTER_DRYRUN_RESULT_v1 검증 결과에 따라 참고용 문구로 교체
const SECTOR_ENVIRONMENT_41 = {
  "_meta": {
    "generated_at": "2026-10-06",
    "description": "읽기 전용 · ETF 섹터 환경 필터 스냅샷. 매수/매도 신호 아님 — 신규 진입 속도 조절용 참고정보.",
    "declaration": "ETF_ENV_FILTER_DECLARATION_v1_20261007.md"
  },
  "tickers": {
    "AAPL": {
      "ticker": "AAPL",
      "as_of": "2026-10-06",
      "primary_etf": "XLK",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 2.2,
      "stock_vs_primary_etf_relative_strength_pct": -3.59,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "AMAT": {
      "ticker": "AMAT",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 5.07,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "AMD": {
      "ticker": "AMD",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 24.43,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "AMZN": {
      "ticker": "AMZN",
      "as_of": "2026-10-06",
      "primary_etf": "XLY",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -8.44,
      "stock_vs_primary_etf_relative_strength_pct": 1.92,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "ANET": {
      "ticker": "ANET",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -0.41,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "ARM": {
      "ticker": "ARM",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 8.47,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "ASML": {
      "ticker": "ASML",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -4.6,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "AVGO": {
      "ticker": "AVGO",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -6.55,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "BE": {
      "ticker": "BE",
      "as_of": "2026-10-06",
      "primary_etf": "ICLN",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.96,
      "stock_vs_primary_etf_relative_strength_pct": 18.26,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "CEG": {
      "ticker": "CEG",
      "as_of": "2026-10-06",
      "primary_etf": "XLU",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -10.12,
      "stock_vs_primary_etf_relative_strength_pct": 4.94,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "COHR": {
      "ticker": "COHR",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 8.5,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "CRM": {
      "ticker": "CRM",
      "as_of": "2026-10-06",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -19.51,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "EME": {
      "ticker": "EME",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 11.43,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "ETN": {
      "ticker": "ETN",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 10.44,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "FIX": {
      "ticker": "FIX",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 15.0,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "GEV": {
      "ticker": "GEV",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 11.37,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "GOOGL": {
      "ticker": "GOOGL",
      "as_of": "2026-10-06",
      "primary_etf": "XLC",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.0,
      "stock_vs_primary_etf_relative_strength_pct": 3.06,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "HUBB": {
      "ticker": "HUBB",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 7.46,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "INTC": {
      "ticker": "INTC",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 5.88,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "KLAC": {
      "ticker": "KLAC",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -5.16,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "LITE": {
      "ticker": "LITE",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 17.06,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "LRCX": {
      "ticker": "LRCX",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -3.02,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "META": {
      "ticker": "META",
      "as_of": "2026-10-06",
      "primary_etf": "XLC",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -6.0,
      "stock_vs_primary_etf_relative_strength_pct": 20.14,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "MOD": {
      "ticker": "MOD",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": -0.33,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "MRVL": {
      "ticker": "MRVL",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 16.84,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "MSFT": {
      "ticker": "MSFT",
      "as_of": "2026-10-06",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -0.38,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "MU": {
      "ticker": "MU",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -8.7,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "NVDA": {
      "ticker": "NVDA",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -7.7,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "ORCL": {
      "ticker": "ORCL",
      "as_of": "2026-10-06",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": -15.13,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "PLTR": {
      "ticker": "PLTR",
      "as_of": "2026-10-06",
      "primary_etf": "IGV",
      "etf_environment": "돌파 확인",
      "etf_relative_strength_21d_pct": 0.64,
      "stock_vs_primary_etf_relative_strength_pct": 3.87,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "PWR": {
      "ticker": "PWR",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": 17.34,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "QCOM": {
      "ticker": "QCOM",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -4.27,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "SNDK": {
      "ticker": "SNDK",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -16.12,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "STX": {
      "ticker": "STX",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -16.69,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "TSLA": {
      "ticker": "TSLA",
      "as_of": "2026-10-06",
      "primary_etf": "IDRV",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -14.59,
      "stock_vs_primary_etf_relative_strength_pct": 16.44,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "TSM": {
      "ticker": "TSM",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": 0.9,
      "sector_leader": true,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "VRT": {
      "ticker": "VRT",
      "as_of": "2026-10-06",
      "primary_etf": "XLI",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -7.77,
      "stock_vs_primary_etf_relative_strength_pct": -7.66,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "VST": {
      "ticker": "VST",
      "as_of": "2026-10-06",
      "primary_etf": "XLU",
      "etf_environment": "약세/실패",
      "etf_relative_strength_21d_pct": -10.12,
      "stock_vs_primary_etf_relative_strength_pct": 11.96,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    },
    "WDC": {
      "ticker": "WDC",
      "as_of": "2026-10-06",
      "primary_etf": "SMH",
      "etf_environment": "재테스트 성공",
      "etf_relative_strength_21d_pct": 5.89,
      "stock_vs_primary_etf_relative_strength_pct": -23.62,
      "sector_leader": false,
      "original_signal_connected": false,
      "sector_filter_interpretation": "원신호 미연결 — 섹터 환경 참고용",
      "sector_filter_interpretation_detail": "기존 RSI·눌림목·반등 신호에 대한 섹터 ETF 필터의 성과 개선 효과는 현재 검증되지 않았습니다. 시장 문맥 참고용으로만 사용합니다."
    }
  }
};
